
name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots verify
        
      - name: Test with Maven
        run: mvn test
        
      - name: Spike test
        uses: k6io/action@v0.1
        with:
          filename: spiketest.js
          
      - name: Load test
        uses: k6io/action@v0.1
        with:
          filename: loadtest.js
          
      - name: Stress Test
        uses: k6io/action@v0.1
        with:
          filename: stresstest.js    

  publish:
      needs: test
      name: publish
      runs-on: ubuntu-latest
      steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: steijntjuh/postit:latest
